---
title: "Experiments 58-61"
author: "Erik J Peterson"
date: "9-1-2015"
output:
  html_document:
    number_sections: yes
    theme: spacelab
    toc: yes
---

# Exp 58, 59, 61

Are replicates of exp57 except for,
- Exp 58: Ipri = 0.5
- Exp 59: MI with m = 4
- Exp 61: set f0 = 20 Hz

It is change in MI that is of interest.

```{r helper_fns, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(dplyr)
library(reshape)
library(png)

path <- "/home/ejp/src/pacological/data"

load.data <- function(path, type, rates, gs, Ns, pns){
  df <- NULL
  for(r_s in rates){
    for(g in gs){
      for(N in Ns){
        for(pn in pns){
          try({
            name <- paste("Istim-", as.character(r_s), 
                          "_g-", as.character(g),
                          "_N-", as.character(N),
                          "_pn-", as.character(pn),
                          "__", as.character(type), 
                          "_summary.csv", sep="")
            di <- read.csv(paste(path, name, sep=""))
            di["Istim"] <- rep(r_s, nrow(di))
            di["g"] <- rep(g, nrow(di))
            di["N"] <- rep(N, nrow(di))
            di["pn"] <- rep(pn, nrow(di))
            
            df <- rbind(df, di)  
          })  
        }
      }
    }
  }
  df
}

load.all.data <- function(path, type, rates, gs, Ns, pns){
  df <- NULL
  for(r_s in rates){
    for(g in gs){
      for(N in Ns){
        for(pn in pns){
          try({
            name <- paste("Istim-", as.character(r_s), 
                          "_g-", as.character(g),
                          "_N-", as.character(N),
                          "_pn-", as.character(pn),
                          "__", as.character(type), 
                          ".csv", sep="")
            di <- read.csv(paste(path, name, sep=""))
            di["Istim"] <- rep(r_s, nrow(di))
            di["g"] <- rep(g, nrow(di))
            di["N"] <- rep(N, nrow(di))
            di["pn"] <- rep(pn, nrow(di))
            
            df <- rbind(df, di)  
          })  
        }
      }
    }
  }
  df
}

load.demo <- function(path, type, rates, ks){
  dexp <- NULL
  for(r_o in rates){
    for(r_s in rates){
      for(k in ks){
        try({
          name <- paste("Iosc-", as.character(r_o), 
                      "_Istim-", as.character(r_s), 
                      "_k", as.character(k), 
                      "_", as.character(type), 
                      ".csv", sep="")
          di <- read.csv(paste(path, name, sep=""))
          di["Iosc"] <- rep(r_o, nrow(di))
          di["Istim"] <- rep(r_s, nrow(di))
          di["k"] <- rep(k, nrow(di))
          
          dexp <- rbind(dexp, di)  
       })
      }
    }
  }
dexp
}


load.demo2 <- function(path, type, rates, gs, Ns, pns){
  df <- NULL
  for(r_s in rates){
    for(g in gs){
      for(N in Ns){
        for(pn in pns){
          try({
            name <- paste("Istim-", as.character(r_s), 
                          "_g-", as.character(g),
                          "_N-", as.character(N),
                          "_pn-", as.character(pn),
                          "_", as.character(type), 
                          ".csv", sep="")
            di <- read.csv(paste(path, name, sep=""))
            di["Istim"] <- rep(r_s, nrow(di))
            di["g"] <- rep(g, nrow(di))
            di["N"] <- rep(N, nrow(di))
            di["pn"] <- rep(pn, nrow(di))
            
            df <- rbind(df, di)  
          })  
        }
      }
    }
  }
  df
}
```

```{r load58, echo=FALSE, warning=FALSE, message=FALSE}
rates <- c(2, 6, 10, 14, 18, 22, 26, 30)
gs <- c(1,2,3,4,5,6,7,8)
Ns <- c(100, 200, 300, 400, 500)
pns <- c(0.25, 0.5, 0.75, 1)

exp58path <- paste(path, "/exp58/", sep="")
mi_exp58 <- load.data(exp58path, "MI", rates, gs, Ns, pns)
h_exp58 <- load.data(exp58path, "H", rates, gs, Ns, pns)
pac_exp58 <- load.data(exp58path, "PAC", rates, gs, Ns, pns)
```

```{r fig58, fig.width=8, fig.height=5, echo=FALSE, warning=FALSE, message=FALSE}
# -- MI
# Sel N and p
mi_fig58 <- filter(mi_exp58, N == 100, pn == 1.00)

# Get Avg MI for stim
Mstim <- mean((filter(mi_fig58, X == "stim_p"))$mean)
mi_fig58$mean <- mi_fig58$mean - Mstim

# Select, rename, and order 'em
mi_fig58 <- filter(mi_fig58, X %in% c("gain_p", "silenced_p", "summed_p"))
mi_fig58$X <- revalue(mi_fig58$X, c("gain_p"="EI", "summed_p"="E", "silenced_p"="I"))
mi_fig58$X <- factor(mi_fig58$X, levels=c("EI", "E", "I")) 

# Sum and plot
mi_stats <- group_by(mi_fig58, X)
mi_stats <- summarise(mi_stats, M=mean(mean), SD=sd(mean))
limits <- aes(ymax = M + SD, ymin=M - SD)

f58a <- qplot(data=mi_stats, x=X, y=M, geom="bar", stat="identity", width=.75) + geom_errorbar(limits, width=0.2, color="grey") + ylab(expression(paste(Delta, "MI"))) + theme_bw() + geom_hline(yintercept=0, color="grey") + xlab("") + ggtitle("Exp 59")

# 2B, Series
mi_exp58 %>% 
  filter(N == 100, pn == 1.00, X %in% c("gain_p", "silenced_p", "summed_p", "stim_p")) %>%
  droplevels() -> mi_fig58b

mi_fig58b$X <- revalue(mi_fig58b$X, c("gain_p"="EI", "summed_p"="E", "silenced_p"="I", "stim_p"="S"))

# Get subtract mean I_stim
mi_fig58b %>% select(mean, Istim, g, X) %>% 
  group_by(Istim, g, X) %>%
  cast(Istim + g ~ X, value = "mean") %>%
  mutate(E=E - S, I = I - S, EI = EI - S) %>%
  select(-S) %>% 
  melt(id=c('Istim', 'g'), variable_name = 'model') -> mi_stats

mi_stats$model <- revalue(mi_stats$model, c("EI"="EI"))
mi_stats$model <- factor(mi_stats$model, levels=c("EI", "E", "I"))

f58b <- qplot(data=mi_stats, x=Istim, y=value, facets=.~model, color=g, geom="line", group=g) + 
  theme_bw() + 
  xlim(0,30) + 
  ylab(expression(paste(Delta, "MI"))) +
  geom_hline(yintercept=0, color="grey") + 
  xlab(expression(r[s])) +
  theme(strip.background = element_blank(), axis.title.x = element_text(colour = "red")) +
  ggtitle("Exp 58")
# print(f2b)
```

```{r load59, echo=FALSE, warning=FALSE, message=FALSE}
rates <- c(2, 6, 10, 14, 18, 22, 26, 30)
gs <- c(1,2,3,4,5,6,7,8)
Ns <- c(100, 200, 300, 400, 500)
pns <- c(0.25, 0.5, 0.75, 1)

exp59path <- paste(path, "/exp59/", sep="")
mi_exp59 <- load.data(exp59path, "MI", rates, gs, Ns, pns)
h_exp59 <- load.data(exp59path, "H", rates, gs, Ns, pns)
pac_exp59 <- load.data(exp59path, "PAC", rates, gs, Ns, pns)
```

```{r fig59, fig.width=8, fig.height=5, echo=FALSE, warning=FALSE, message=FALSE}
# -- MI
# Sel N and p
mi_fig59 <- filter(mi_exp59, N == 100, pn == 1.00)

# Get Avg MI for stim
Mstim <- mean((filter(mi_fig59, X == "stim_p"))$mean)
mi_fig59$mean <- mi_fig59$mean - Mstim

# Select, rename, and order 'em
mi_fig59 <- filter(mi_fig59, X %in% c("gain_p", "silenced_p", "summed_p"))
mi_fig59$X <- revalue(mi_fig59$X, c("gain_p"="EI", "summed_p"="E", "silenced_p"="I"))
mi_fig59$X <- factor(mi_fig59$X, levels=c("EI", "E", "I")) 

# Sum and plot
mi_stats <- group_by(mi_fig59, X)
mi_stats <- summarise(mi_stats, M=mean(mean), SD=sd(mean))
limits <- aes(ymax = M + SD, ymin=M - SD)

f59a <- qplot(data=mi_stats, x=X, y=M, geom="bar", stat="identity", width=.75) + geom_errorbar(limits, width=0.2, color="grey") + ylab(expression(paste(Delta, "MI"))) + theme_bw() + geom_hline(yintercept=0, color="grey") + xlab("") + ggtitle("Exp 59")

# 2B, Series
mi_exp59 %>% 
  filter(N == 100, pn == 1.00, X %in% c("gain_p", "silenced_p", "summed_p", "stim_p")) %>%
  droplevels() -> mi_fig59b

mi_fig59b$X <- revalue(mi_fig59b$X, c("gain_p"="EI", "summed_p"="E", "silenced_p"="I", "stim_p"="S"))

# Get subtract mean I_stim
mi_fig59b %>% select(mean, Istim, g, X) %>% 
  group_by(Istim, g, X) %>%
  cast(Istim + g ~ X, value = "mean") %>%
  mutate(E=E - S, I = I - S, EI = EI - S) %>%
  select(-S) %>% 
  melt(id=c('Istim', 'g'), variable_name = 'model') -> mi_stats

mi_stats$model <- revalue(mi_stats$model, c("EI"="EI"))
mi_stats$model <- factor(mi_stats$model, levels=c("EI", "E", "I"))

f59b <- qplot(data=mi_stats, x=Istim, y=value, facets=.~model, color=g, geom="line", group=g) + 
  theme_bw() + 
  xlim(0,30) + 
  ylab(expression(paste(Delta, "MI"))) +
  geom_hline(yintercept=0, color="grey") + 
  xlab(expression(r[s])) +
  theme(strip.background = element_blank(), axis.title.x = element_text(colour = "red")) +
  ggtitle("Exp 59")
# print(f2b)
```

```{r load61, echo=FALSE, warning=FALSE, message=FALSE}
rates <- c(2, 6, 10, 14, 18, 22, 26, 30)
gs <- c(1,2,3,4,5,6,7,8)
Ns <- c(100, 200, 300, 400, 500)
pns <- c(0.25, 0.5, 0.75, 1)

exp61path <- paste(path, "/exp61/", sep="")
mi_exp61 <- load.data(exp61path, "MI", rates, gs, Ns, pns)
h_exp61 <- load.data(exp61path, "H", rates, gs, Ns, pns)
pac_exp61 <- load.data(exp61path, "PAC", rates, gs, Ns, pns)
```

```{r fig61, fig.width=10, fig.height=6, echo=FALSE, warning=FALSE, message=FALSE}
# -- MI
# Sel N and p
mi_fig61<- filter(mi_exp59, N == 100, pn == 1.00)

# Get Avg MI for stim
Mstim <- mean((filter(mi_fig61, X == "stim_p"))$mean)
mi_fig61$mean <- mi_fig61$mean - Mstim

# Select, rename, and order 'em
mi_fig61<- filter(mi_fig61, X %in% c("gain_p", "silenced_p", "summed_p"))
mi_fig61$X<- revalue(mi_fig61$X, c("gain_p"="EI", "summed_p"="E", "silenced_p"="I"))
mi_fig61$X<- factor(mi_fig61$X, levels=c("EI", "E", "I")) 

# Sum and plot
mi_stats <- group_by(mi_fig61, X)
mi_stats <- summarise(mi_stats, M=mean(mean), SD=sd(mean))
limits <- aes(ymax = M + SD, ymin=M - SD)

f61a <- qplot(data=mi_stats, x=X, y=M, geom="bar", stat="identity", width=.75) + geom_errorbar(limits, width=0.2, color="grey") + ylab(expression(paste(Delta, "MI"))) + theme_bw() + geom_hline(yintercept=0, color="grey") + xlab("") + ggtitle("Exp 61")

# 2B, Series
mi_exp59 %>% 
  filter(N == 100, pn == 1.00, X %in% c("gain_p", "silenced_p", "summed_p", "stim_p")) %>%
  droplevels() -> mi_fig61b

mi_fig61b$X <- revalue(mi_fig61b$X, c("gain_p"="EI", "summed_p"="E", "silenced_p"="I", "stim_p"="S"))

# Get subtract mean I_stim
mi_fig61b %>% select(mean, Istim, g, X) %>% 
  group_by(Istim, g, X) %>%
  cast(Istim + g ~ X, value = "mean") %>%
  mutate(E=E - S, I = I - S, EI = EI - S) %>%
  select(-S) %>% 
  melt(id=c('Istim', 'g'), variable_name = 'model') -> mi_stats

mi_stats$model <- revalue(mi_stats$model, c("EI"="EI"))
mi_stats$model <- factor(mi_stats$model, levels=c("EI", "E", "I"))

f61b <- qplot(data=mi_stats, x=Istim, y=value, facets=.~model, color=g, geom="line", group=g) + 
  theme_bw() + 
  xlim(0,30) + 
  ylab(expression(paste(Delta, "MI"))) +
  geom_hline(yintercept=0, color="grey") + 
  xlab(expression(r[s])) +
  theme(strip.background = element_blank(), axis.title.x = element_text(colour = "red")) +
  ggtitle("Exp 61")
# print(f2b)

grid.arrange(f58a, f58b, f59a, f59b, f61a, f61b, nrow=3)
```

* Private noise had no effect on deltaMI
* Changing `m` from 8 to 4 had no effect on deltaMI.
* Change of F from 6 to 20 hz has no effect on deltaMI.


# Exp 60 - Ozkurt PAC

```{r load60, echo=FALSE, warning=FALSE, message=FALSE}
rates <- c(2, 6, 10, 14, 18, 22, 26, 30)
gs <- c(1,2,3,4,5,6,7,8)
Ns <- c(100, 200, 300, 400, 500)
pns <- c(0.25, 0.5, 0.75, 1)

exp60path <- paste(path, "/exp60/", sep="")
mi_exp60 <- load.data(exp60path, "MI", rates, gs, Ns, pns)
h_exp60 <- load.data(exp60path, "H", rates, gs, Ns, pns)
pac_exp60 <- load.data(exp60path, "PAC", rates, gs, Ns, pns)
```

```{r fig60, fig.width=10, fig.height=2, echo=FALSE, warning=FALSE, message=FALSE}
# -- PAC
# -- MI
# Sel N and p
pac_fig60 <- filter(pac_exp60, N == 100, pn == 1.00)

# Select, rename, and order 'em
pac_fig60 <- filter(pac_fig60, X %in% c("gain_p", "silenced_p", "summed_p", "stim_p"))
pac_fig60$X <- revalue(pac_fig60$X, c("gain_p"="EI", "summed_p"="E", "silenced_p"="I", "stim_p"="S"))
pac_fig60$X <- factor(pac_fig60$X, levels=c("S", "EI", "E", "I")) 

# Sum and plot
pac_fig60 %>% group_by(X) %>% summarise(M=mean(mean), SD=sd(mean)) -> pac_stats
limits <- aes(ymax = M + SD, ymin=M - SD)

f60a <- qplot(data=pac_stats, x=X, y=M, geom="bar", stat="identity", width=.75) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  ylab("OZ") + theme_bw() + 
  geom_hline(yintercept=0, color="grey") + 
  xlab("")

# -------
# 3B, Series
pac_exp60 %>% 
  filter(N == 100, pn == 1.00, X %in% c("gain_p", "silenced_p", "summed_p", "stim_p")) %>%
  droplevels()  %>% select(X, mean, std, Istim, g, N, pn) -> pac_fig60b

pac_fig60b$X <- revalue(pac_fig60b$X, c("gain_p"="EI", "summed_p"="E", "silenced_p"="I", "stim_p"="S"))
pac_fig60b$X <- factor(pac_fig60b$X, levels=c("S", "EI", "E", "I"))
f60b0 <- qplot(data=pac_fig60b, x=Istim, y=mean, facets=.~X, color=g, geom="line", group=g) + 
  theme_bw() + 
  xlim(0,30) + 
  ylab("OZ") +
  geom_hline(yintercept=0, color="grey") + 
  xlab(expression(r[s])) +
  theme(strip.background = element_blank(), axis.title.x = element_text(colour = "red"))

grid.arrange(f60a, f60b0, nrow=1)
```

* While absolute magnitudes differ, the relative pattern of results between Ozkurt and PLV (exp57) measures is the same.

